[lint]
line-length = 99
ignore = ["PLR0904", "PLR0912", "PLR0913", "PLR0914", "PLR0916", "PLW0603", "G004", "E402", "D203", "D213", "D404"]
# PLR0904: class has too many public methods (default: 20)
# PLR0912: function or method has too many logical branches (default: 12)
# PLR0913: function or method takes too many arguments (default: 5)
# PLR0914: function or method has too many local variables (default: 15)
# PLR0916: if-statement contains too many boolean expressions (default: 5)
# PLW0603: global statement used to update a global variable
# G004: logging statement uses f-string
# E402: module level imports should be at the top of the file
# D203: 1 blank line required before class docstring
# D213: multi-line docstring summary should start at the second line
# D404: first word of the docstring should not be "This"
