"""Abstract base class for the handling of workflow DAGs."""

from abc import ABC, abstractmethod


class GraphDatabaseDriver(ABC):
    """Driver interface for a generic graph database.

    The driver must implement a __init__ method that creates/connects to
    the graph database and returns some kind of 'connection' interface object.
    """

    @abstractmethod
    def initialize_workflow(self, workflow):
        """Begin construction of a workflow in the graph database.

        :param workflow: the workflow description
        :type workflow: Workflow
        """

    @abstractmethod
    def execute_workflow(self):
        """Begin execution of the stored workflow.

        Set the initial tasks' states to 'READY'.
        """

    @abstractmethod
    def pause_workflow(self):
        """Pause execution of a running workflow.

        Set tasks with state 'RUNNING' to 'PAUSED'.
        """

    @abstractmethod
    def resume_workflow(self):
        """Resume execution of a paused workflow.

        Set tasks with state 'PAUSED' to 'RUNNING'.
        """

    @abstractmethod
    def reset_workflow(self, new_id):
        """Reset the execution state of a workflow.

        Set all task states to 'WAITING'.
        Change the workflow ID of the Workflow and Task nodes with new_id.

        :param new_id: the new workflow ID
        :type new_id: str
        """

    @abstractmethod
    def load_task(self, task):
        """Load a task into a stored workflow.

        Dependencies should be automatically deduced and generated by the graph database
        upon loading each task by matching task inputs and outputs.

        :param task: a workflow task
        :type task: Task
        """

    @abstractmethod
    def initialize_ready_tasks(self):
        """Set runnable tasks to state 'READY'.

        Runnable tasks are tasks with all dependency tasks'
        states set to 'COMPLETED'.
        """

    @abstractmethod
    def get_task_by_id(self, task_id):
        """Return a workflow task record from the graph database.

        :param task_id: a task's ID
        :type task_id: str
        :rtype: Task
        """

    @abstractmethod
    def get_workflow_description(self):
        """Return a reconstructed Workflow object from the graph database.

        :rtype: Workflow
        """
    @abstractmethod
    def get_workflow_tasks(self):
        """Return a list of all workflow task records from the graph database.

        :rtype: set of Task
        """

    @abstractmethod
    def get_workflow_requirements_and_hints(self):
        """Return all workflow requirements and hints from the graph database.

        Must return a tuple with the format (requirements, hints)

        :rtype: (set of Requirement, set of Hint)
        """

    @abstractmethod
    def get_subworkflow_tasks(self, subworkflow):
        """Return subworkflow tasks from the graph database.

        :param subworkflow: the unique identifier of the subworkflow
        :type subworkflow: str
        :rtype: set of Task
        """

    @abstractmethod
    def get_ready_tasks(self):
        """Return tasks with state 'READY' from the graph database.

        :rtype: set of Task
        """

    @abstractmethod
    def get_dependent_tasks(self, task):
        """Return the dependent tasks of a workflow task in the graph database.

        :param task: the task whose dependents to retrieve
        :type task: Task
        :rtype: set of Task
        """

    @abstractmethod
    def get_task_state(self, task):
        """Return the state of a task in the graph database workflow.

        :param task: the task whose status to retrieve
        :type task: Task
        :rtype: str
        """

    @abstractmethod
    def set_task_state(self, task, state):
        """Set the state of a task in the graph database workflow.

        :param task: the task whose state to set
        :type task: Task
        :param state: the new state
        :type state: str
        """

    @abstractmethod
    def get_task_metadata(self, task, keys):
        """Return the metadata of a task in the graph database workflow.

        :param task: the task whose metadata to retrieve
        :type task: Task
        :param keys: the metadata keys whose values to retrieve
        :type keys: iterable of str
        :rtype: dict
        """

    @abstractmethod
    def set_task_metadata(self, task, metadata):
        """Set the metadata of a task in the graph database workflow.

        :param task: the task whose metadata to set
        :type task: Task
        :param metadata: the job description metadata
        :type metadata: dict
        """

    @abstractmethod
    def workflow_completed(self):
        """Determine if a workflow has completed.

        A workflow has completed if each of its tasks has state 'COMPLETED'.

        :rtype: bool
        """

    @abstractmethod
    def empty(self):
        """Determine if the database is empty.

        :rtype: bool
        """

    @abstractmethod
    def cleanup(self):
        """Clean up all the data stored in the graph database."""

    @abstractmethod
    def close(self):
        """Close the connection to the graph database."""
