#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

yum install -y autoconf automake bison byacc cscope ctags diffstat doxygen elfutils flex gcc-c++ gcc-gfortran indent intltool libtool patchutils rcs redhat-rpm-config rpm-build rpm-sign subversion swig systemtap apr apr-util bzip2 dwz dyninst emacs-filesystem gdb gettext-common-devel gettext-devel libdwarf libgfortran libquadmath libquadmath-devel libstdc++-devel neon pakchois perl-Data-Dumper perl-Test-Harness perl-Thread-Queue perl-XML-Parser perl-srpm-macros subversion-libs systemtap-client systemtap-devel systemtap-runtime unzip puppet ansible python-ceilometerclient python-cinderclient python-glanceclient python-heatclient python-neutronclient python-novaclient python-openstackclient python-ceilometerclient-doc python-cinderclient-doc python-glanceclient-doc python-heatclient-doc python-keystoneclient python-keystoneclient-doc python-novaclient-doc python-swiftclient python-swiftclient-doc libguestfs-tools supervisor python-amqp python-psutil redhat-lsb-core

# Missing dependency os-collect-config
yum install -y python2-oslo-log

# Install missing firmware
yum install -y linux-firmware
