heat_template_version: 2013-05-23

description: >
  Template based on https://github.com/openstack/heat-templates/blob/master/hot/servers_in_new_neutron_net.yaml

parameters:
  key_name:
    type: string
    description: Key name
  public_net:
    type: string
    description: Public network name
  github_pat:
    type: string
    description: GitHub PAT credential for cloning BEE
  git_branch:
    type: string
    description: git branch to checkout
  https_proxy:
    type: string
    description: HTTPS proxy url
  http_proxy:
    type: string
    description: HTTP proxy url
  no_proxy:
    type: string
    description: no proxy urls to set in environment
  nameservers:
    type: string
    description: list of nameservers separated by commas
  wfm_listen_port:
    type: string
    description: WFM listen port
  tm_listen_port:
    type: string
    description: TM listen port
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: bee-net
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: '10.93.78.0/24'
      gateway_ip: '10.93.78.1'
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }
  server:
    type: OS::Nova::Server
    properties:
      name: bee-server
      # Custom snapshot with everything preinstalled
      image: 'debian-10-openstack-amd64'
      flavor: 'm1.small'
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
      user_data:
        str_replace:
          template: { get_file: dora-setup.sh }
          # Parameters added as input above need also be added here for
          # replacement
          params:
            $GITHUB_PAT: { get_param: github_pat }
            $USER: debian
            $GIT_BRANCH: { get_param: git_branch }
            $HTTPS_PROXY: { get_param: https_proxy }
            $HTTP_PROXY: { get_param: http_proxy }
            $NO_PROXY: { get_param: no_proxy }
            $NAMESERVERS: { get_param: nameservers }
            $WFM_LISTEN_PORT: { get_param: wfm_listen_port }
            $TM_LISTEN_PORT: { get_param: tm_listen_port }
  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server_port }
outputs:
  server_public_ip:
    value: { get_attr: [server_floating_ip, floating_ip_address] }
