"""Graph database driver using SQLite as the backend."""

import os
from beeflow.common.gdb.gdb_driver import GraphDatabaseDriver
from beeflow.common.config_driver import BeeConfig as bc
from beeflow.common.db.gdb_db import SQL_GDB

def db_path():
    """Return the SQL GDB database path."""
    bee_workdir = bc.get('DEFAULT', 'bee_workdir')
    return os.path.join(bee_workdir, 'gdb_sql.db')

def connect_db():
    """Connect to the SQL GDB database."""
    return SQL_GDB(db_path())



class SQLDriver(GraphDatabaseDriver):
    """Graph database driver using SQLite as the backend."""

    def __new__(cls):
        if not hasattr(cls, 'instance'):
            cls.instance = super(SQLDriver, cls).__new__(cls)
        return cls.instance

    def connect(self):
        """Connect to the graph database."""
        if not hasattr(self, 'db'):
            self.db = connect_db() # pylint: disable=W0201


    def initialize_workflow(self, workflow):
        """Begin construction of a workflow in the graph database.

        Should create the Workflow, Requirement, and Hint nodes in the graph database.

        :param workflow: the workflow description
        :type workflow: Workflow
        """
        self.db.create_workflow(workflow)


    def execute_workflow(self, workflow_id):
        """Begin execution of the stored workflow.

        Set the initial tasks' states to 'READY'.
        """
        self.db.set_init_task_inputs(workflow_id)
        self.db.set_runnable_tasks_to_ready(workflow_id)


    def pause_workflow(self, workflow_id):
        """Pause execution of a running workflow.

        Set workflow from state 'RUNNING' to 'PAUSED'.
        """
        self.db.set_workflow_state(workflow_id, 'PAUSED')


    def resume_workflow(self, workflow_id):
        """Resume execution of a paused workflow.

        Set workflow state from 'PAUSED' to 'RUNNING'.
        """
        self.db.set_workflow_state(workflow_id, 'RUNNING')


    def load_task(self, task):
        """Load a task into a stored workflow.

        Dependencies should be automatically deduced and generated by the graph database
        upon loading each task by matching workflow inputs with new task inputs,
        or task outputs with new task inputs.

        :param task: a workflow task
        :type task: Task
        """
        self.db.create_task(task)
        self.db.add_dependencies(task)


    def initialize_ready_tasks(self, workflow_id):
        """Set runnable tasks to state 'READY'.

        Runnable tasks are tasks with all input dependencies fulfilled.
        """
        self.db.set_runnable_tasks_to_ready(workflow_id)


    def restart_task(self, old_task, new_task):
        """Restart a failed task.

        Create a Task node for new_task with state 'RESTARTED' and an edge
        to indicate that it is the child of the Task node of old_task.

        :param old_task: the failed task
        :type old_task: Task
        :param new_task: the new (restarted) task
        :type new_task: Task
        """
        self.db.create_task(new_task)
        self.db.set_task_state(new_task.id, 'WAITING')
        self.db.add_dependencies(new_task, old_task=old_task, restarted_task=True)


    def finalize_task(self, task):
        """Set task state to 'COMPLETED' and set inputs from source.

        :param task: the task to finalize
        :type task: Task
        """
        self.db.set_task_state(task.id, 'COMPLETED')
        self.db.copy_task_outputs(task)


    def get_task_by_id(self, task_id):
        """Return a reconstructed Task object from the graph database by its ID.

        :param task_id: a task's ID
        :type task_id: str
        :rtype: Task
        """
        return self.db.get_task(task_id)


    def get_all_workflow_info(self):
        """Return a list of all workflows in the graph database.

        :rtype: list of workflowinfo
        """
        return self.db.get_all_workflow_info()


    def get_workflow_description(self, workflow_id):
        """Return a reconstructed Workflow object from the graph database.

        :rtype: Workflow
        """
        return self.db.get_workflow(workflow_id)


    def get_workflow_state(self, workflow_id):
        """Return the current state of the workflow.

        :rtype: str
        """
        return self.db.get_workflow_state(workflow_id)


    def set_workflow_state(self, workflow_id, state):
        """Set the state of the workflow.

        :param state: the new state of the workflow
        :type state: str
        """
        self.db.set_workflow_state(workflow_id, state)


    def get_workflow_tasks(self, workflow_id):
        """Return a list of all workflow tasks from the graph database.

        :rtype: list of Task
        """
        return self.db.get_workflow_tasks(workflow_id)


    def get_workflow_requirements_and_hints(self, workflow_id):
        """Return all workflow requirements and hints from the graph database.

        Must return a tuple with the format (requirements, hints)

        :rtype: (list of Requirement, list of Hint)
        """
        return self.db.get_workflow_requirements_and_hints(workflow_id)


    def get_workflow_inputs_and_outputs(self, workflow_id):
        """Return all workflow inputs and outputs from the graph database.

        Returns a tuple of (inputs, outputs).

        :rtype: (list of InputParameter, list of OutputParameter)
        """
        return (self.db.get_workflow_inputs(workflow_id),
                self.db.get_workflow_outputs(workflow_id))


    def get_ready_tasks(self, workflow_id):
        """Return tasks with state 'READY' from the graph database.

        :rtype: list of Task
        """
        return self.db.get_ready_tasks(workflow_id)


    def get_dependent_tasks(self, task_id):
        """Return the dependent tasks of a workflow task in the graph database.

        :param task_id: the ID of the task whose dependents to retrieve
        :type task_id: str
        :rtype: list of Task
        """
        return self.db.get_dependent_tasks(task_id)


    def get_task_state(self, task_id):
        """Return the state of a task in the graph database.

        :param task_id: the ID of the task whose status to retrieve
        :type task_id: str
        :rtype: str
        """
        return self.db.get_task_state(task_id)


    def set_task_state(self, task_id, state):
        """Set the state of a task in the graph database.

        :param task_id: the ID of the task whose state to set
        :type task_id: str
        :param state: the new state
        :type state: str
        """
        self.db.set_task_state(task_id, state)


    def get_task_metadata(self, task_id):
        """Return the metadata of a task in the graph database.

        :param task_id: the ID of the task whose metadata to retrieve
        :type task_id: str
        :rtype: dict
        """
        return self.db.get_task_metadata(task_id)


    def set_task_metadata(self, task_id, metadata):
        """Set the metadata of a task in the graph database.

        :param task_id: the ID of the task whose metadata to set
        :type task_id: str
        :param metadata: the job description metadata
        :type metadata: dict
        """
        self.db.set_task_metadata(task_id, metadata)


    def get_task_input(self, task_id, input_id):
        """Get a task input object.

        :param task_id: the ID of the task whose input to retrieve
        :type task_id: str
        :param input_id: the ID of the input
        :type input_id: str
        :rtype: StepInput
        """
        return self.db.get_task_input(task_id, input_id)


    def set_task_input(self, task_id, input_id, value):
        """Set the value of a task input.

        :param task_id: the ID of the task whose input to set
        :type task_id: str
        :param input_id: the ID of the input
        :type input_id: str
        :param value: str or int or float
        """
        self.db.set_task_input(task_id, input_id, value)


    def get_task_output(self, task_id, output_id):
        """Get a task output object.

        :param task_id: the ID of the task whose output to retrieve
        :type task_id: str
        :param output_id: the ID of the output
        :type output_id: str
        :rtype: StepOutput
        """
        return self.db.get_task_output(task_id, output_id)


    def set_task_output(self, task_id, output_id, value):
        """Set the value of a task output.

        :param task_id: the ID of the task whose output to set
        :type task_id: str
        :param output_id: the ID of the output
        :type output_id: str
        :param value: the output value to set
        :type value: str or int or float
        """
        self.db.set_task_output(task_id, output_id, value)


    def set_task_input_type(self, task_id, input_id, type_):
        """Set the type of a task input.

        :param task_id: the ID of the task whose input type to set
        :type task_id: str
        :param input_id: the ID of the input
        :type input_id: str
        :param type_: the input type to set
        :param type_: str
        """
        self.db.set_task_input_type(task_id, input_id, type_)


    def set_task_output_glob(self, task_id, output_id, glob):
        """Set the glob of a task output.

        :param task_id: the ID of the task whose output glob to set
        :type task_id: str
        :param output_id: the ID of the output
        :type output_id: str
        :param glob: the output glob to set
        :type glob: str
        """
        self.db.set_task_output_glob(task_id, output_id, glob)


    def workflow_completed(self, workflow_id):
        """Determine if a workflow has completed.

        A workflow has completed if each of its final tasks has finished or failed.

        :rtype: bool
        """
        return self.db.final_tasks_completed(workflow_id)


    def get_workflow_final_state(self, workflow_id):
        """Get the final state of the workflow.

        :rtype: Optional[str]
        """
        final_state = None
        if self.db.final_tasks_succeeded(workflow_id):
            final_state = None
        elif self.db.final_tasks_failed(workflow_id):
            final_state = 'Failed'
        elif self.db.final_tasks_completed(workflow_id):
            final_state = 'Partial-Fail'
        else:
            raise ValueError(f"Workflow with id {workflow_id} has not finished.")
        return final_state


    def cancelled_workflow_completed(self, workflow_id: str) -> bool:
        """Determine if a cancelled workflow has completed.

        A cancelled workflow has completed if each of its final tasks are not
        'PENDING', 'RUNNING' 'COMPLETING'.

        :rtype: bool
        """
        return self.db.cancelled_final_tasks_completed(workflow_id)


    def remove_workflow(self, workflow_id):
        """Remove a workflow from the graph database.

        :param workflow_id: the ID of the workflow to remove
        :type workflow_id: str
        """
        self.db.remove_workflow(workflow_id)


    def close(self):
        """Close the graph database connection."""


    def export_graphml(self, workflow_id):
        """Export a BEE workflow as a graphml."""
        raise NotImplementedError("GraphML export not implemented for SQLite GDB.")
