# Dockerfile.clamr-ffmpeg


FROM debian:12


RUN apt-get update && \
    apt-get install -y wget gnupg git cmake ffmpeg g++ make openmpi-bin \
            libopenmpi-dev libpng-dev libpng16-16 libpng-tools imagemagick \
            libmagickwand-6.q16-6 libmagickwand-6.q16-dev

RUN git clone https://github.com/lanl/CLAMR.git

# Remove sys/sysctl.h from modern Linux systems; is not needed here.
RUN sed -i '/sys\/sysctl\.h/d' /CLAMR/memstats/memstats.c

RUN cd CLAMR && cmake . && make clamr_cpuonly
