name: Build Docs

on:
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, edited]
    branches: [main, develop]

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install BEE and Build Docs
        run: ./ci/docs.sh
