name: Integration workflow

on:
  # For manual exec
  # (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
    branches: [main, develop]

env: {}

jobs:
  integration-test:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'WIP (no-ci)')) && !(contains(github.event.pull_request.labels.*.name, 'WIP (lint-only)')) }}
    name: BEE Integration Test
    strategy:
      matrix:
        bee_worker: [Slurmrestd, SlurmCommands, Flux]
      fail-fast: False
    env:
      BEE_WORKER: ${{ matrix.bee_worker }}
    # Note: Needs to run on 22.04 or later since slurmrestd doesn't seem to be
    # available on 20.04
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v4
      - name: Install and Configure
        run: |
          . ./ci/env.sh
          ./ci/deps_install.sh
          ./ci/batch_scheduler.sh
          ./ci/bee_install.sh
          ./ci/bee_config.sh
      - name: Integration Test
        run: |
          . ./ci/env.sh
          ./ci/integration_test.sh
