# Based on https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: Publish docs

on:
  push:
    branches: [main]

# Needed for publishing to Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: BEE Install and Build Docs
        run: |
          ./ci/docs.sh
      - name: Upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/sphinx/_build/html
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v1
