name: Ruff Lint

on:
  # For manual exec
  # (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
    branches: [main, develop]

jobs:
  ruff:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'WIP (no-ci)')) }}
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          pip install ruff==0.9.0 2>&1 >/dev/null
          ruff check beeflow/
