name: Testing, Coverage, and Build Docs

permissions:
  contents: read

on:
  # For manual exec
  # (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
    branches: [main, develop]

env: {}

jobs:
  integration-test:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'WIP (no-ci)')) && !(contains(github.event.pull_request.labels.*.name, 'WIP (lint-only)')) }}
    name: BEE Integration Test
    strategy:
      fail-fast: false
      matrix:
        bee_worker: [Slurmrestd, SlurmCommands, Flux]
        # TODO get neo4j test to work again
        # gdb_backend: [neo4j, sqlite3]
        gdb_backend: [sqlite3]
    env:
      BEE_WORKER: ${{ matrix.bee_worker }}
      GDB_BACKEND: ${{ matrix.gdb_backend }}
    # Note: Needs to run on 22.04 or later since slurmrestd doesn't seem to be
    # available on 20.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Install Initial Dependencies  
        run: ./ci/deps_install.sh

      - name: Install Flux Dependencies 
        if: env.BEE_WORKER == 'Flux'
        run: ./ci/flux_deps.sh

      - name: Restore Slurm and Charliecloud Installs 
        id: cache-installs-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ github.workspace }}/charliecloud
            ${{ github.workspace }}/slurm
          key: ${{ runner.os }}-installs-${{ hashFiles('./ci/env.sh','./ci/charliecloud_install.sh','./ci/slurm_install.sh') }} 

      - name: Build Slurm and Charliecloud for Save
        if: ${{ steps.cache-installs-restore.outputs.cache-hit != 'true' }}
        run: |
          . ./ci/env.sh
          ./ci/charliecloud_install.sh
          ./ci/slurm_install.sh

      - name: Save Slurm and Charliecloud Installs
        if: ${{ steps.cache-installs-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ github.workspace }}/charliecloud
            ${{ github.workspace }}/slurm
          key: ${{ steps.cache-installs-restore.outputs.cache-primary-key }}

      - name: Move Slurm and Charliecloud Installs
        run: |
          sudo cp -r ${{ github.workspace }}/charliecloud/. /usr
          sudo cp -r ${{ github.workspace }}/slurm/. /usr

      - name: Restore Flux Install
        if: ${{ env.BEE_WORKER == 'Flux' }}
        id: cache-flux-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/flux
          key: ${{ runner.os }}-flux-${{ hashFiles('./ci/env.sh','./ci/flux.sh') }} 

      - name: Build Flux Install for Save
        if: steps.cache-flux-restore.outputs.cache-hit != 'true' && env.BEE_WORKER == 'Flux'
        run: |
          . ./ci/env.sh
          ./ci/flux_install.sh

      - name: Save Flux Install
        if: steps.cache-flux-restore.outputs.cache-hit != 'true' && env.BEE_WORKER == 'Flux' 
        uses: actions/cache/save@v5
        with:
          path: ${{ github.workspace }}/flux
          key: ${{ steps.cache-flux-restore.outputs.cache-primary-key }}

      - name: Move Flux Install 
        run: |
          sudo cp -f ${{ github.workspace }}/flux/. /usr
          if [[ "${{ steps.cache-flux-restore.outputs.cache-hit }}" == "true" ]]; then
            sudo ldconfig
          fi 

      - name: Install Flux Python Bindings
        if: env.BEE_WORKER == 'Flux'
        run: |
          . ./ci/env.sh
          python3 -m pip install --user wheel
          python3 -m pip install --user flux-python==$FLUX_CORE_VERSION

      - name: Install and Configure
        run: |
          . ./ci/env.sh
          echo "LOG_DIR=$LOG_DIR" >> $GITHUB_ENV
          echo "SLURM_CONF=$SLURM_CONF" >> $GITHUB_ENV
          echo "BEE_WORKDIR=$BEE_WORKDIR" >> $GITHUB_ENV
          echo "BEE_CONFIG=$BEE_CONFIG" >> $GITHUB_ENV 
          ./ci/batch_scheduler.sh
          ./ci/bee_install.sh
          ./ci/bee_config.sh

      - name: Integration Test
        run: |
          . ./ci/env.sh
          ./ci/integration_test.sh
          mv .coverage.integration ".coverage.${{ matrix.bee_worker }}.${{ matrix.gdb_backend }}"

      - name: Stash bee error logs
        if: failure()   # only when the job fails
        run: |
          mkdir bee-error-logs
          cp bee-error-*.log bee-error-logs || true
          cp -R $LOG_DIR bee-error-logs || true
          cp -R $SLURM_CONF bee-error-logs || true
          cp -R $BEE_WORKDIR/logs bee-error-logs || true
          cp -R $BEE_WORKDIR/*.db bee-error-logs || true
          cp -R $BEE_CONFIG bee-error-logs || true

      - name: Upload bee error logs
        if: failure()    # only when the job fails
        uses: actions/upload-artifact@v5
        with:
          name: bee-error-logs-${{ matrix.bee_worker }}-${{ matrix.gdb_backend }}
          path: bee-error-logs
          if-no-files-found: ignore

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-${{ matrix.bee_worker }}-${{ matrix.gdb_backend }}
          include-hidden-files: true
          path: ".coverage.${{ matrix.bee_worker }}.${{ matrix.gdb_backend }}"

  unit-test:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'WIP (no-ci)')) && !(contains(github.event.pull_request.labels.*.name, 'WIP (lint-only)')) }}
    name: BEE Unit Tests
    env:
      # Unit tests are only run with slurmrestd right now
      BEE_WORKER: Slurmrestd
    # Note: Needs to run on 22.04 or later since slurmrestd doesn't seem to be
    # available on 20.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Install Initial Dependencies 
        run: ./ci/deps_install.sh

      - name: Restore Slurm and Charliecloud Installs
        id: cache-installs-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ github.workspace }}/charliecloud
            ${{ github.workspace }}/slurm
          key: ${{ runner.os }}-installs-${{ hashFiles('./ci/env.sh','./ci/charliecloud_install.sh','./ci/slurm_install.sh') }}

      - name: Build Slurm and Charliecloud for Save
        if: ${{ steps.cache-installs-restore.outputs.cache-hit != 'true' }}
        run: |
          . ./ci/env.sh
          ./ci/charliecloud_install.sh
          ./ci/slurm_install.sh

      - name: Save Slurm and Charliecloud Installs
        if: ${{ steps.cache-installs-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ github.workspace }}/charliecloud
            ${{ github.workspace }}/slurm
          key: ${{ steps.cache-installs-restore.outputs.cache-primary-key }}

      - name: Move Slurm and Charliecloud Installs
        run: |
          sudo cp -r ${{ github.workspace }}/charliecloud/. /usr
          sudo cp -r ${{ github.workspace }}/slurm/. /usr

      - name: Install and Configure
        run: |
          . ./ci/env.sh
          ./ci/batch_scheduler.sh
          ./ci/bee_install.sh
          ./ci/bee_config.sh

      - name: Unit tests
        run: |
          . ./ci/env.sh
          ./ci/unit_tests.sh
          mv .coverage ".coverage.unittests"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-unit-tests
          include-hidden-files: true
          path: ".coverage.unittests"

  coverage:
    needs: [integration-test, unit-test]
    name: Coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get unit test coverage
        uses: actions/download-artifact@v6
        with:
          name: coverage-unit-tests
          path: ./

      # - name: Get Slurmrestd+neo4j coverage
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: coverage-Slurmrestd-neo4j
      #     path: ./
      
      - name: Get Slurmrestd+sqlite3 coverage
        uses: actions/download-artifact@v6
        with:
          name: coverage-Slurmrestd-sqlite3
          path: ./
      
      # - name: Get SlurmCommands+neo4j coverage
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: coverage-SlurmCommands-neo4j
      #     path: ./
      
      - name: Get SlurmCommands+sqlite3 coverage
        uses: actions/download-artifact@v6
        with:
          name: coverage-SlurmCommands-sqlite3
          path: ./
      
      # - name: Get Flux+neo4j coverage
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: coverage-Flux-neo4j
      #     path: ./
      
      - name: Get Flux+sqlite3 coverage
        uses: actions/download-artifact@v6
        with:
          name: coverage-Flux-sqlite3
          path: ./

      - name: Combine coverage
        run: |
          pip install coverage
          coverage combine
          coverage report --show-missing
       
      - name: Add coverage to job summary
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          coverage report --show-missing >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Coverage Badge
        run: |
          coverage xml
          pip install -U genbadge defusedxml
          genbadge coverage -i coverage.xml -o coverage.svg

      - name: Upload coverage badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: ./coverage.svg

      - name: Coverage comment
        id: coverage
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-xml-coverage-path: coverage.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report"
          hide-emoji: true
          hide-report: true
          create-new-comment: true

      - name: Low coverage job summary
        run: |
          coverage report --fail-under=65

      - name: Prepare coverage badge for GitHub Pages
        if: github.event_name == 'push'
        run: |
          mkdir -p badge-publish
          cp coverage.svg badge-publish/coverage.svg

      - name: Publish coverage badge
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./badge-publish
          destination_dir: badges/${{ github.ref_name }}
          keep_files: true

  build-and-publish-docs:
    if: ${{ always() }}
    needs: [coverage]
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : Checkout latest tag for main
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch --tags --force
          LATEST_TAG="$(git tag --sort=-creatordate | head -n 1)"
          echo "Latest tag: $LATEST_TAG"
          git checkout "$LATEST_TAG"

      - name: Install BEE and Build Docs
        run: ./ci/docs.sh

      - name: Publish latest docs to root
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/sphinx/_build/html
          destination_dir: .
          keep_files: true
