name: Integration workflow

on:
  # For manual exec
  # (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch: {}
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
    branches: [main, develop]

env: {}

jobs:
  test:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'WIP') || contains(github.event.pull_request.labels.*.name, 'lint-only')) }}
    name: BEE Unit and Integration Tests
    # Note: Needs to run on 22.04 or later since slurmrestd doesn't seem to be
    # available on 20.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependency Install
        run: ./ci/deps_install.sh
      - name: Slurm Setup and Install
        run: ./ci/slurm_start.sh
      - name: BEE Install
        run: ./ci/bee_install.sh
      - name: BEE Start
        run: ./ci/run.sh ./ci/bee_start.sh
      - name: Unit Tests
        run: ./ci/run.sh ./ci/unit_tests.sh
      - name: Integration Test
        run: ./ci/run.sh ./ci/integration_test.sh
